name: CMD-microwgs
channels:
    - bioconda
    - conda-forge
    - defaults

dependencies:
    - bioconda::sambamba=0.8.1
    - bioconda::samtools
    - bioconda::picard=2.26.6
    - bioconda::perl-app-cpanminus==1.7044
