Bootstrap:docker
From:nfcore/base:latest

%labels
	MAINTAINER Isak Sylvin <isak.sylvin@scilifelab.se>
	DESCRIPTION Singularity container for JASEN microbiology WGS pipeline
	VERSION 0.0.1

%environment
	PATH=/opt/conda/envs/jasen/bin/:$PATH
	umask 0002

%files
        environment.yml /

%post
	/opt/conda/bin/conda env create -f /environment.yml

%runscript
	exec "$@"`
