Bootstrap:docker
From:ubuntu

%labels
	MAINTAINER Isak Sylvin <isak.sylvin@scilifelab.se>
	DESCRIPTION Singularity container for JASEN microbiology WGS pipeline
	VERSION 0.1.0

%environment
	umask 0002

%files
        environment.yml /

%post
        apt -y update
        apt -y install build-essential make curl 
        #apt -y install openjdk-11-jre:amd64
        mkdir /scratch/
	/opt/conda/bin/conda env create -f /environment.yml
        #curl -s https://get.nextflow.io | /bin/bash
        #mv nextflow /bin/ 
        git clone https://github.com/genomic-medicine-sweden/JASEN.git 


%runscript
        /opt/conda/bin/conda activate jasen
	exec "$@"`
        /opt/conda/bin/conda deactivate
